In [1]:
aList = ["John", 33, "Toronto", True]
aList

['John', 33, 'Toronto', True]

In [2]:
type (aList)

list

In [3]:
bin_colors=('Red', 'Green', 'Blue', 'Yellow')

In [4]:
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [5]:
print(f"The element after third element onwards are {bin_colors[2:]}")

The element after third element onwards are ('Blue', 'Yellow')


In [6]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


In [7]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [8]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [9]:
bin_colors.get('approved_color')

'Green'

In [10]:
bin_colors['approved_color']

'Green'

In [11]:
bin_colors['approved_color']="Purple"

In [13]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [14]:
green = {'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [15]:
yellow ={'dandelions','fire hydrant','leaves'}
red = {'fire hydrant','blood','rose','leaves'}

In [16]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'fire hydrant', 'rose', 'blood', 'leaves', 'dandelions'}


In [17]:
print(f"The intersaction of yellow and red sets is {yellow&red}")

The intersaction of yellow and red sets is {'leaves', 'fire hydrant'}


In [18]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [19]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [20]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [21]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [22]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [23]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [24]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [25]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [26]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])